name: spiroble
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  csv: ^5.0.0
  path_provider: ^2.0.14
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  firebase_storage: ^12.3.0
  cloud_firestore: ^5.4.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  flutter_svg: ^1.0.0
  cupertino_icons: ^1.0.8
  flutter_reactive_ble: ^5.3.1
  get: ^4.6.5
  permission_handler: ^10.0.0
  flutter_blue_plus: ^1.16.2
  flutter_ble_peripheral: ^1.2.6
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  flutter_provider: ^2.1.0
  flutter_riverpod: ^2.6.1
  firebase_database: ^11.1.6
  fancy_button_flutter: ^1.0.3+1
  percent_indicator: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/spiroicons.svg"  # Doğru ikon dosyasını buraya yerleştirin

flutter_lints: ^4.0.0

flutter:

  assets:
    - assets/
    - assets/parameters.csv
    - assets/ikincitablo.csv
    - assets/logo.png
    - assets/lungs.svg
    - assets/breath.svg
    - assets/spiroicons.svg
    - assets/entry.svg
    - assets/spirometer.svg
    - assets/images/bluetooth_connected.jpg

  uses-material-design: true
